import { mkdir, appendFile, writeFile, access } from "node:fs/promises";
import path from "node:path";

export async function ensureDir(dirPath: string): Promise<void> {
  await mkdir(dirPath, { recursive: true });
}

async function ensureGitignore(eyes4aiDir: string): Promise<void> {
  const gitignorePath = path.join(eyes4aiDir, ".gitignore");
  try {
    await access(gitignorePath);
  } catch {
    await writeFile(gitignorePath, "# Auto-generated by eyes4ai — keep this directory out of git\n*\n", "utf8");
  }
}

export async function appendJsonLine(filePath: string, value: unknown): Promise<void> {
  await ensureDir(path.dirname(filePath));
  // Drop a .gitignore in the .eyes4ai root if it doesn't exist
  const parts = filePath.split(path.sep);
  const idx = parts.lastIndexOf(".eyes4ai");
  if (idx !== -1) {
    const eyes4aiDir = parts.slice(0, idx + 1).join(path.sep);
    await ensureGitignore(eyes4aiDir);
  }
  await appendFile(filePath, `${JSON.stringify(value)}\n`, "utf8");
}

export function todayJsonlPath(rootDir: string): string {
  const isoDay = new Date().toISOString().slice(0, 10);
  return path.join(rootDir, ".eyes4ai", "private", "events", `${isoDay}.jsonl`);
}
