import { writeFile, access, readFile } from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { ensureDir } from "./fs-utils.js";

const BEGIN_MARKER = "# eyes4ai:begin";
const END_MARKER = "# eyes4ai:end";

function codexConfig(endpoint: string): string {
  return [
    BEGIN_MARKER,
    "[otel]",
    "environment = \"dev\"",
    "log_user_prompt = false",
    `exporter = { otlp-http = { endpoint = \"${endpoint}/v1/logs\", protocol = \"json\" } }`,
    "trace_exporter = \"none\"",
    "metrics_exporter = \"none\"",
    "",
    "# Generated by eyes4ai for local dogfooding.",
    END_MARKER
  ].join("\n");
}

function upsertManagedBlock(current: string, block: string): string {
  const start = current.indexOf(BEGIN_MARKER);
  const end = current.indexOf(END_MARKER);

  if (start !== -1 && end !== -1 && end > start) {
    const before = current.slice(0, start).trimEnd();
    const after = current.slice(end + END_MARKER.length).trimStart();
    return [before, block, after].filter((part) => part.length > 0).join("\n\n");
  }

  if (current.includes("[otel]")) {
    return `${current.trimEnd()}\n\n${block}\n`;
  }

  return current.trim().length > 0 ? `${current.trimEnd()}\n\n${block}\n` : `${block}\n`;
}

async function upsertConfigFile(configPath: string, endpoint: string): Promise<void> {
  let alreadyExists = false;
  try {
    await access(configPath);
    alreadyExists = true;
  } catch {
    alreadyExists = false;
  }

  if (alreadyExists) {
    const current = await readFile(configPath, "utf8");
    await writeFile(configPath, upsertManagedBlock(current, codexConfig(endpoint)), "utf8");
  } else {
    await writeFile(configPath, codexConfig(endpoint), "utf8");
  }
}

/** Install Codex OTel config into the repo-local .codex/config.toml. */
export async function installCodexOtelConfig(rootDir: string, endpoint: string): Promise<string> {
  const codexDir = path.join(rootDir, ".codex");
  await ensureDir(codexDir);
  const configPath = path.join(codexDir, "config.toml");
  await upsertConfigFile(configPath, endpoint);
  return configPath;
}

/** Install Codex OTel config into the global ~/.codex/config.toml. */
export async function installCodexOtelConfigGlobal(endpoint: string): Promise<string> {
  const codexDir = path.join(os.homedir(), ".codex");
  await ensureDir(codexDir);
  const configPath = path.join(codexDir, "config.toml");
  await upsertConfigFile(configPath, endpoint);
  return configPath;
}
